server:
  port: 8081
  
logging:
  file:
    name: logs/studentapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG
    '[com.springboot]': DEBUG
    
management:
 endpoints:
  web: 
     exposure:
          include: ['trace','auditevents','threaddump','configprops','health','env','metrics','logfile','loggers' , 'beans']